### ISSUE TITLE
move functionality to pipeline-service

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-json-filter#13]
in order to consolidate the amount of actions needed, we could/should move the functionality to the helix-pipeline-service.

- both read the content-bus to get the data
- both are used for delivery

currently it's a bit tricky with the old request params. better wait for:
https://github.com/adobe/helix-pipeline-service/issues/58

**Comment by trieloff** [comment]
I'm not a fan of this idea:
- the number of functions is not a problem per se
- the feature set of pipeline and json filter is very different, and so is the output format
- keeping the JSON filter in a separate function makes it more manageable when we decide to move the functionality into the edge

**Comment by tripodsan** [comment]
> * the number of functions is not a problem per se

it is an additional _burden_ when managing the versions that rely on the content structure. like in the recent content-bus migration.

> * the feature set of pipeline and json filter is very different, and so is the output format

in helix2, we also had the json processing in the pipeline (well... not a strong point, I know :-)

> * keeping the JSON filter in a separate function makes it more manageable when we decide to move the functionality into the edge

we can easily remove it again.

**Comment by tripodsan** [comment]
also, it simplifies the VCL logic by removing a special case.

**Comment by tripodsan** [comment]
done.
